
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usuario
 */
public class persona extends javax.swing.JFrame {
    conectar cc = new conectar();
    Connection cn = cc.getConnection();
    public static String id,persona;
    /**
     * Creates new form persona
     */
    public persona() {
        initComponents();
        this.setLocationRelativeTo(null);
        cerrar();
    }
    public void cerrar(){
        try{
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e){
                    confirmarSalida();
                }
            });
            this.setVisible(true);
        } catch (Exception e){
            e.printStackTrace();
        }
    }
    public void confirmarSalida(){
        int valor1 = JOptionPane.showConfirmDialog(this,"¿Esta seguro de salir de la Aplicacion?","Advertencia",JOptionPane.YES_NO_OPTION);
        if(valor1 == JOptionPane.YES_OPTION){
//            JOptionPane.showMessageDialog(null,"GRacias por su visita!","Gracias", JOptionPane.INFORMATION_MESSAGE);
//            System.exit(0);
            Inicio in = new Inicio();
            in.setVisible(true);
            this.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idPersona = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        cbPersona = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbPersona = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("persona");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPersonaActionPerformed(evt);
            }
        });
        idPersona.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idPersonaKeyTyped(evt);
            }
        });
        getContentPane().add(idPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 136, -1));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 140, -1));

        cbPersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CLIENTE", "EMPLEADO", "PROVEEDOR" }));
        cbPersona.setToolTipText("");
        cbPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPersonaActionPerformed(evt);
            }
        });
        getContentPane().add(cbPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 160, -1));

        jButton1.setText("Consultar");
        jButton1.setMaximumSize(new java.awt.Dimension(75, 32));
        jButton1.setMinimumSize(new java.awt.Dimension(75, 32));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 130, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Ingrese la cedula o ruc de la Persona a Registrar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, 30));

        lbPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/au2.jpg"))); // NOI18N
        getContentPane().add(lbPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        
        id=idPersona.getText();
        persona = cbPersona.getSelectedItem().toString();
        if (id.equals("")){
            javax.swing.JOptionPane.showMessageDialog(this,"ingrese cedula o ruc \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                idPersona.requestFocus();
        }else{
            try{
                PreparedStatement pst=cn.prepareStatement("INSERT INTO Persona(id) VALUES(?)");
                pst.setString(1,idPersona.getText());

                int a=pst.executeUpdate();
                if(a>0 && persona.equalsIgnoreCase("EMPLEADO") ){
                    JOptionPane.showMessageDialog(null,"Registro exitoso");
                    
                    REmpleado re = new REmpleado();
                    re.setVisible(true);
                    this.setVisible(false);
                }else if(a>0 && persona.equalsIgnoreCase("CLIENTE")){
                    JOptionPane.showMessageDialog(null,"Registro exitoso");
                    
                    RCliente rc = new RCliente();
                    rc.setVisible(true);
                    this.setVisible(false);
                }else if(a>0 && persona.equalsIgnoreCase("PROVEEDOR")){
                    JOptionPane.showMessageDialog(null,"Registro exitoso");
                    
                    RProveedor rp = new RProveedor();
                    rp.setVisible(true);
                    this.setVisible(false);
                }else{
                    JOptionPane.showMessageDialog(null,"Error al agregar");
                }
            }catch(Exception e){
            }  
        }// TODO
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void idPersonaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idPersonaKeyTyped
        // TODO add your handling code here:
        char e = evt.getKeyChar();
        if(e<'0' || e>'9') {
            evt.consume();
        }
    }//GEN-LAST:event_idPersonaKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CPersona cp = new CPersona();
        cp.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void idPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idPersonaActionPerformed

    private void cbPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPersonaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new persona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JComboBox<String> cbPersona;
    private javax.swing.JTextField idPersona;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbPersona;
    // End of variables declaration//GEN-END:variables
}
