
import java.awt.HeadlessException;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usuario
 */
public class RFViaje extends javax.swing.JFrame {
    conectar cc = new conectar();
    Connection cn = cc.getConnection();
    java.util.Date fecha;
    java.sql.Date fecha_m;
    public static int codFactura, codViaje;
    public static float valor;
    public String des,Cliente,codCliente,precio,articulo;
    /**
     * Creates new form RFViaje
     */
    public RFViaje() {
        initComponents();
        mostrarCliente(cbCliente);
        mostrarViajes(cbViaje);
        this.setLocationRelativeTo(null);
        cerrar();
    }
    public void cerrar(){
        try{
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e){
                    confirmarSalida();
                }
            });
            this.setVisible(true);
        } catch (Exception e){
            e.printStackTrace();
        }
    }
    public void confirmarSalida(){
        int valor1 = JOptionPane.showConfirmDialog(this,"¿Esta seguro de salir de la Aplicacion?","Advertencia",JOptionPane.YES_NO_OPTION);
        if(valor1 == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null,"GRacias por su visita!","Gracias", JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
    }
    public int id(){
        int id=1;
        String sql = "SELECT MAX(num_defactura) FROM factura_viaje";
        try {
            
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                id=rs.getInt(1) +1 ;
            }
        } catch (SQLException ex) {
            Logger.getLogger(RFViaje.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;
    }
    public void mostrarViajes(JComboBox cb_Viaje){
       
        String sql = "SELECT * FROM Viaje";
        String cod = null;
        
                try{
                    Statement st = cn.createStatement();
                    ResultSet rs = st.executeQuery(sql);
                    cbViaje.removeAllItems();
                    while(rs.next()){
                        cod = rs.getString(1);
                        
        
                             cbViaje.addItem(cod);
     
                    }        
                } catch (SQLException ex) {
                    Logger.getLogger(REmpleado.class.getName()).log(Level.SEVERE, null, ex);
                }        
    }
    public void mostrarCliente(JComboBox cb_Cliente){
       
        String sql = "SELECT * FROM Cliente";
        String nombre = null;
        
                try{
                    Statement st = cn.createStatement();
                    ResultSet rs = st.executeQuery(sql);
                    cbCliente.removeAllItems();
                    while(rs.next()){
                        nombre = rs.getString(2);
                        
        
                             cbCliente.addItem(nombre);
     
                    }        
                } catch (SQLException ex) {
                    Logger.getLogger(RCliente.class.getName()).log(Level.SEVERE, null, ex);
                }        
    }
    private String CodCliente(){
        String nombre= cbCliente.getSelectedItem().toString();
        String id = "";
        String sql = "SELECT id FROM Cliente WHERE nombreCliente = '"+nombre+"'";
        try {
            
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                id=rs.getString(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(RProveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;  
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_titulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lb_primerNombre = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        cbCliente = new javax.swing.JComboBox<>();
        btnActualizar = new javax.swing.JButton();
        lb_idEmpleado1 = new javax.swing.JLabel();
        cbDate = new com.toedter.calendar.JDateChooser();
        lb_idEmpleado2 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        lb_idEmpleado3 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        lb_primerNombre1 = new javax.swing.JLabel();
        cbViaje = new javax.swing.JComboBox<>();
        lb_idEmpleado4 = new javax.swing.JLabel();
        txtArticulo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jmenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jPrincipla = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_titulo.setBackground(new java.awt.Color(0, 0, 0));
        lb_titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lb_titulo.setForeground(new java.awt.Color(0, 0, 0));
        lb_titulo.setText("REGISTRO DE FACTURA VIAJES");
        getContentPane().add(lb_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lb_primerNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_primerNombre.setForeground(new java.awt.Color(0, 0, 0));
        lb_primerNombre.setText("Valor:");

        btnguardar.setText("GUARDAR");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        cbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "EMPLEADO", "PROVEEDOR" }));
        cbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClienteActionPerformed(evt);
            }
        });

        btnActualizar.setText("Consultar Registro");
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        lb_idEmpleado1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_idEmpleado1.setForeground(new java.awt.Color(0, 0, 0));
        lb_idEmpleado1.setText("Fecha:");

        lb_idEmpleado2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_idEmpleado2.setForeground(new java.awt.Color(0, 0, 0));
        lb_idEmpleado2.setText("Cliente:");

        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorKeyTyped(evt);
            }
        });

        lb_idEmpleado3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_idEmpleado3.setForeground(new java.awt.Color(0, 0, 0));
        lb_idEmpleado3.setText("Descripcion:");

        lb_primerNombre1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_primerNombre1.setForeground(new java.awt.Color(0, 0, 0));
        lb_primerNombre1.setText("cod Viaje:");

        lb_idEmpleado4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_idEmpleado4.setForeground(new java.awt.Color(0, 0, 0));
        lb_idEmpleado4.setText("Articulo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lb_idEmpleado3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lb_idEmpleado1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbDate, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lb_idEmpleado2)
                                    .addGap(35, 35, 35)
                                    .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_primerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_primerNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(txtValor)))
                            .addComponent(lb_idEmpleado4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lb_idEmpleado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_idEmpleado4)
                        .addComponent(txtArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_idEmpleado2)
                    .addComponent(lb_primerNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_idEmpleado3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_primerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardar)
                    .addComponent(btnActualizar))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 560, 220));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/au2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 6, 740, 490));

        jMenu1.setText("Archivo");

        jPrincipla.setText("Menu");
        jPrincipla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrinciplaActionPerformed(evt);
            }
        });
        jMenu1.add(jPrincipla);

        jmenu.add(jMenu1);

        setJMenuBar(jmenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPrinciplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrinciplaActionPerformed
        // TODO add your handling code here:
        Inicio in = new Inicio();
        in.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jPrinciplaActionPerformed
    
    private static java.sql.Date convertUtilToSql(java.util.Date uDate) {
        java.sql.Date sDate = new java.sql.Date(uDate.getTime());
	return sDate;
    }
    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        fecha = cbDate.getDate();
        fecha_m = convertUtilToSql(fecha);
        Cliente = cbCliente.getSelectedItem().toString();
        des = txtDescripcion.getText();
        codViaje = Integer.parseInt(cbViaje.getSelectedItem().toString());
        precio = txtValor.getText();
        valor = Integer.parseInt(precio);
        codFactura = id();
        codCliente = CodCliente();
        articulo = txtArticulo.getText();

        PreparedStatement pst = null;
        //           String sql = "INSERT INTO Empleado VALUES(?,?,?,?,?,?)";

        if(Cliente.equals("")|| des.equals("")|| precio.equals("")|| articulo.equals("")){
            javax.swing.JOptionPane.showMessageDialog(this,"Debe llenar todos los campos \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            cbViaje.requestFocus();

        }else {

            try{

                pst=cn.prepareStatement("INSERT INTO factura_viaje(num_defactura,fecha_registro,descripcion,valor,articulo,viaje,cliente) VALUES(?,?,?,?,?,?,?)");
                pst.setInt(1,codFactura);//tfidPersona.getText());
            pst.setDate(2,fecha_m);
            pst.setString(3,des);
            pst.setFloat(4,valor);
            pst.setString(5,articulo);
            pst.setInt(6,codViaje);
            pst.setString(7,codCliente);

            //                    JOptionPane.showMessageDialog(null, "Empleado"+ id +"Registrado" );

            int a=pst.executeUpdate();
            if(a>0){
                JOptionPane.showMessageDialog(null,"Registro exitoso");
            }else{
                JOptionPane.showMessageDialog(null,"Error al agregar");
            }
        }catch(HeadlessException | SQLException ex){
            Logger.getLogger(RVehiculo.class.getName()).log(Level.SEVERE, null, ex);
        }

        finally {
            if (cn != null) {
                try {
                    cn.close();
                    pst.close();
                } catch ( SQLException e ) {
                    System.out.println( e.getMessage());
                }
            }
        }

        javax.swing.JOptionPane.showMessageDialog(this,"Registro exitoso! \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }

        this.cbCliente.setSelectedItem("");
        this.cbViaje.setSelectedItem("");
        this.txtDescripcion.setText("");
        this.txtValor.setText("");
        this.txtArticulo.setText("");

    }//GEN-LAST:event_btnguardarActionPerformed

    private void cbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClienteActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbClienteActionPerformed

    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        CFactura cf = new CFactura();
        cf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyTyped
        // TODO add your handling code here:
        char e = evt.getKeyChar();
        if(e<'0' || e>'9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtValorKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RFViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RFViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RFViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RFViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RFViaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JComboBox<String> cbCliente;
    private com.toedter.calendar.JDateChooser cbDate;
    private javax.swing.JComboBox<String> cbViaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jPrincipla;
    private javax.swing.JMenuBar jmenu;
    private javax.swing.JLabel lb_idEmpleado1;
    private javax.swing.JLabel lb_idEmpleado2;
    private javax.swing.JLabel lb_idEmpleado3;
    private javax.swing.JLabel lb_idEmpleado4;
    private javax.swing.JLabel lb_primerNombre;
    private javax.swing.JLabel lb_primerNombre1;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JTextField txtArticulo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
