
import java.awt.HeadlessException;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usuario
 */
public class RViaje extends javax.swing.JFrame {
    public static int cod, cVehiculo;
    public static String Des,idEmpleado,ruta,vehiculo,empleado;
    java.util.Date llegada1,salida1;
    java.sql.Date llegada,salida;
    conectar cc = new conectar();
    Connection cn = cc.getConnection();
    /**
     * Creates new form RViaje
     */
    public RViaje() {
        initComponents();
         mostrarVehiculos(cbVehiculo);
         mostrarEmpleado(cbEmpleado);
        this.setLocationRelativeTo(null);
        cerrar();
    }
    public void cerrar(){
        try{
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e){
                    confirmarSalida();
                }
            });
            this.setVisible(true);
        } catch (Exception e){
            e.printStackTrace();
        }
    }
    public void confirmarSalida(){
        int valor1 = JOptionPane.showConfirmDialog(this,"¿Esta seguro de salir de la Aplicacion?","Advertencia",JOptionPane.YES_NO_OPTION);
        if(valor1 == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null,"GRacias por su visita!","Gracias", JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
    }
    public int idViaje(){
        int id=1;
        String sql = "SELECT MAX(codigo) FROM Viaje";
        try {
            
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                id=rs.getInt(1) +1 ;
            }
        } catch (SQLException ex) {
            Logger.getLogger(RViaje.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;
    }
    public void mostrarVehiculos(JComboBox cb_Vehiculo){
        
        String sql = "SELECT * FROM Vehiculo";
        String placa= null;
                try{
                    Statement st = cn.createStatement();
                    ResultSet rs = st.executeQuery(sql);
                    cbVehiculo.removeAllItems();
                    while(rs.next()){
                        placa = rs.getString(2);
                        cbVehiculo.addItem(placa);
     
                    }        
                } catch (SQLException ex) {
                    Logger.getLogger(RVehiculo.class.getName()).log(Level.SEVERE, null, ex);
                }        
    }
     public void mostrarEmpleado(JComboBox cb_Empleado){
       
        String sql = "SELECT * FROM Empleado";
        String nombre = null;
        String apellido = null;
                try{
                    Statement st = cn.createStatement();
                    ResultSet rs = st.executeQuery(sql);
                    cbEmpleado.removeAllItems();
                    while(rs.next()){
                        nombre = rs.getString(2);
                        apellido = rs.getString(4);
        
                             cbEmpleado.addItem(nombre + " "+ apellido);
     
                    }        
                } catch (SQLException ex) {
                    Logger.getLogger(REmpleado.class.getName()).log(Level.SEVERE, null, ex);
                }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_titulo = new javax.swing.JLabel();
        lblMatricula = new javax.swing.JLabel();
        lb_Salida = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        lb_Llegada = new javax.swing.JLabel();
        lb_Llegada1 = new javax.swing.JLabel();
        cbEmpleado = new javax.swing.JComboBox<>();
        lblMatricula1 = new javax.swing.JLabel();
        cbVehiculo = new javax.swing.JComboBox<>();
        lb_Salida1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Descripcion = new javax.swing.JTextArea();
        date_salida = new com.toedter.calendar.JDateChooser();
        date_llegada = new com.toedter.calendar.JDateChooser();
        cbRuta = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jmenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jPrincipla = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lb_titulo.setBackground(new java.awt.Color(0, 0, 0));
        lb_titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lb_titulo.setText("REGISTRO DE VIAJES");

        lblMatricula.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMatricula.setForeground(new java.awt.Color(0, 0, 0));
        lblMatricula.setText("Ruta:");

        lb_Salida.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_Salida.setForeground(new java.awt.Color(0, 0, 0));
        lb_Salida.setText("Fecha de Saliga:");

        btnguardar.setText("GUARDAR");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Consultar Registro");
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        lb_Llegada.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_Llegada.setForeground(new java.awt.Color(0, 0, 0));
        lb_Llegada.setText("Fecha de llegada:");

        lb_Llegada1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_Llegada1.setForeground(new java.awt.Color(0, 0, 0));
        lb_Llegada1.setText("Empleado:");

        lblMatricula1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMatricula1.setForeground(new java.awt.Color(0, 0, 0));
        lblMatricula1.setText("Vehiculo:");

        cbVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVehiculoActionPerformed(evt);
            }
        });

        lb_Salida1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_Salida1.setForeground(new java.awt.Color(0, 0, 0));
        lb_Salida1.setText("Decripcion:");

        txt_Descripcion.setColumns(20);
        txt_Descripcion.setRows(5);
        jScrollPane1.setViewportView(txt_Descripcion);

        date_salida.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        date_llegada.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbRuta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guayaqui-Manta", "Manta-La Mana", "Manta-Guayaquil" }));
        cbRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRutaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lb_Llegada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date_llegada, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lb_Salida)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(date_salida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblMatricula1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15)
                                        .addComponent(lb_Llegada1)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblMatricula)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbRuta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(lb_Salida1))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(lb_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lb_titulo)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Llegada1)
                    .addComponent(cbEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMatricula1)
                    .addComponent(cbVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMatricula)
                    .addComponent(cbRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(lb_Salida))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(date_salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(lb_Salida1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_Llegada)
                            .addComponent(date_llegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnguardar))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 620, 260));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/au2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 490));

        jMenu1.setText("Archivo");

        jPrincipla.setText("Menu");
        jPrincipla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrinciplaActionPerformed(evt);
            }
        });
        jMenu1.add(jPrincipla);

        jmenu.add(jMenu1);

        setJMenuBar(jmenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPrinciplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrinciplaActionPerformed
        // TODO add your handling code here:
        Inicio in = new Inicio();
        in.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jPrinciplaActionPerformed

    private int CodVehiculo(){
        String placa= cbVehiculo.getSelectedItem().toString();
        int id=0;
        String sql = "SELECT codVehiculo FROM Vehiculo  WHERE matricula = '"+placa+"'";
        try {
            
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                id=rs.getInt(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(RVehiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;  
    } 
     private String CodEmpleado(){
        String nombre= cbEmpleado.getSelectedItem().toString();
        String id = "";
        String sql = "SELECT id FROM Empleado WHERE concat(primer_nombre, \" \" , primer_apeelido) = '"+nombre+"'";
        try {
            
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                id=rs.getString(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(REmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;  
    } 
    
    private static java.sql.Date convertUtilToSql(java.util.Date uDate) {
        java.sql.Date sDate = new java.sql.Date(uDate.getTime());
	return sDate;
    }
    
    
    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        cod = idViaje();
        Des = txt_Descripcion.getText();
        llegada1 = date_llegada.getDate();
        llegada = convertUtilToSql(llegada1);
        salida1 = date_salida.getDate();
        salida = convertUtilToSql(salida1);
        cVehiculo = CodVehiculo();
        idEmpleado = CodEmpleado();
        ruta = cbRuta.getSelectedItem().toString();
        vehiculo = cbVehiculo.getSelectedItem().toString();
        empleado = cbEmpleado.getSelectedItem().toString();

        PreparedStatement pst = null;
        //           String sql = "INSERT INTO Empleado VALUES(?,?,?,?,?,?)";

        if(llegada.equals("")||salida.equals("")||ruta.equals("")||vehiculo.equals("")||empleado.equals("")){
            javax.swing.JOptionPane.showMessageDialog(this,"Debe llenar todos los campos \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            cbVehiculo.requestFocus();

        }else {

            try{

                pst=cn.prepareStatement("INSERT INTO Viaje(codigo,ruta,fecha_salida,fecha_llegada,descripcion_viaje,empleado,vehiculo,codVehiculo) VALUES(?,?,?,?,?,?,?,?)");
                pst.setInt(1,cod);
                pst.setString(2,ruta);
                pst.setDate(3,salida);
                pst.setDate(4,llegada);
                pst.setString(5,Des);
                pst.setString(6,idEmpleado);
                pst.setString(7,vehiculo);
                pst.setInt(8,cVehiculo);

            //                    JOptionPane.showMessageDialog(null, "Empleado"+ id +"Registrado" );

            int a=pst.executeUpdate();
            if(a>0){
                cbVehiculo.removeItem(vehiculo);
                cbEmpleado.removeItem(empleado);
                JOptionPane.showMessageDialog(null,"Registro exitoso");
            }else{
                JOptionPane.showMessageDialog(null,"Error al agregar");
            }
        }catch(HeadlessException | SQLException ex){
            Logger.getLogger(RViaje.class.getName()).log(Level.SEVERE, null, ex);
        }

        finally {
            if (cn != null) {
                try {
                    cn.close();
                    pst.close();
                } catch ( SQLException e ) {
                    System.out.println( e.getMessage());
                }
            }
        }

        javax.swing.JOptionPane.showMessageDialog(this,"Registro exitoso! \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }

//        this.cbVehiculo.setSelectedItem(" ");
//        this.cbEmpleado.setSelectedItem(" ");
//        this.cbRuta.setSelectedItem(" ");
//        this.date_salida.setDate(salida);
//        this.date_llegada.setDate(llegada);
//        this.txt_Descripcion.setText(" ");
        
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        CViaje cv = new CViaje();
        cv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void cbVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVehiculoActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cbVehiculoActionPerformed

    private void cbRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRutaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RViaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JComboBox<String> cbEmpleado;
    private javax.swing.JComboBox<String> cbRuta;
    private javax.swing.JComboBox<String> cbVehiculo;
    private com.toedter.calendar.JDateChooser date_llegada;
    private com.toedter.calendar.JDateChooser date_salida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jPrincipla;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar jmenu;
    private javax.swing.JLabel lb_Llegada;
    private javax.swing.JLabel lb_Llegada1;
    private javax.swing.JLabel lb_Salida;
    private javax.swing.JLabel lb_Salida1;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblMatricula1;
    private javax.swing.JTextArea txt_Descripcion;
    // End of variables declaration//GEN-END:variables
}
